### ISSUE TITLE
Working with proteins not curated in a database

### ISSUE THREAD

**Issue by naphtap** [JoanaMPereira/GCsnap#1]
Hello, 
I'm trying to start using GCSnap, and the example files worked fine. I have an assembled, annotated genome that has a series of hypothetical proteins I'm interested in examining further. I would like to examine the genomic context of these hypothetical proteins against other organisms. However, my annotated genome hasn't been curated in NCBI yet and I would like to explore the genomic context of the hypothetical proteins further. 

Is there a way for me to run GCSnap without needing a database identifier for the hypothetical proteins?

Thanks!

**Comment by JoanaMPereira** [comment]
Dear Naphtap,

Thanks for reaching out! 

In its current version, GCsnap can not deal with user-input assemblies or proteins without a database identifier, but that is definitely in the to-do list. 

If your hypothetical proteins have homologs with a database identifier, my suggestion in this case would be to use GCsnap for those and then compare with the context in your assembly...

Thanks a lot for using GCsnap! 

Cheers,
Joana

**Comment by naphtap** [comment]
Thanks Joana for your help. I'll go ahead with this! Here's hoping you do make an update to add our own assemblies in the future!
